### ISSUE TITLE
stim table has strings instead of valid data?

### ISSUE THREAD

**Issue by rcpeene** [AllenInstitute/OpenScopeNWB#144]
I was attempting to select stimulus times in Dendritic Coupling files, and several of the columns appear not to have valid data, but instead have strings that say `ndarray(...)`. I had thought that this was just a print representation of arrays that exist within that location on the table, but upon further investigation, it appears these are actually _strings_ that say this, not real arrays.

**Comment by jeromelecoq** [comment]
We are not going to worry about merging into the main brain of the allensdk and fix in the fork

**Comment by Ahad-Allen** [comment]
Unfortunately, it seems like the issue is present in the pkl file rather than the nwb conversion code. Jerome and I have looked at the files at length and found the following:
1. Viewing the stimuli section of the pkl file and looking at the 'stim' key shows that some information is being packaged as strings which merely say ndarray(...). I.e. ['stimuli'][6]['stim'] returns the following: 

![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/87045911/96703ff6-c7c6-4350-adc8-1b327f8bef90)


2. This appears to only affect the gabors fields of the stim pickle.
3. The Oris of each Gabor, the seed, and the rng state are preserved in the following location:

![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/87045911/ffc01240-1a73-4dfc-ba86-643daf3dd1c9)


4. Unfortunately, it seems like the size and position are lost (pottentially the SQs too?)
5. The Oris information is currently missing from the nwb files, despite being in the above mentioned section of the pkl file.

**Comment by Ahad-Allen** [comment]
The team indicated that the seed is sufficient for now. We may need to add the seed to the nwb files in the future, but as long as they can be provided the seed number to regen the gabors, they are happy.
