### ISSUE TITLE
Integrate Extract capsule with the denoising and NWB workflow in code ocean

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#166]
The team has switched to using extract, currently working on packaging the extract files into nwb format.

**Comment by jeromelecoq** [comment]
We are now focusing on adding fields from Extract output in the NWB. 
Ahad is working with Tim to test this with NeuroConv. We might need to append the file.

**Comment by Ahad-Allen** [comment]
Jerome and I decided that the best approach is to make the file using neuroconv and then create a custom extention for the config and info fields.

**Comment by Ahad-Allen** [comment]
We do not need to use a custom extention! We are using the https://github.com/catalystneuro/ndx-extract/tree/d58ed03f9eb26cde360879d1ae6a5e328fe51fa4 to handle packaging info from the output files into the nwb. :)

**Comment by Ahad-Allen** [comment]
There is an issue related to the filters field of the extract input file. In the meantime, we have successfully been able to append the relevant metadata to the nwb files :). I've asked the dendrite team about the filters field, but there might be a slight delay in their response since it is thanksgiving there.

**Comment by jeromelecoq** [comment]
Done
