### ISSUE TITLE
Develop a process to store two-photon high definition stack into NWB files.

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#61]
Ophys is acquiring X,Y, Z stacks around the imaging plane of each brain area to visualize dendritic process from deep to superficial layers. This is complementary to calcium imaging data. 

1. We need to evaluate Natalia's notebook for accessing the raw data. 
2. Discuss a strategy to store this stack in NWB files
3. Develop notebook to access stack data in NWB files.

**Comment by Ahad-Allen** [comment]
Since it's a series of tif files, 3d arrays should be sufficient to store all the information. We are unsure of whether the best practice here is to use NWB files to store the stacks, append the information into our current nwb files, or use BIDS just for the stack info. I've contacted Ben and Satra about best approaches for accessing and packaging this data.

**Comment by Ahad-Allen** [comment]
BIDS seems like an inappropriate choice for this use case, as it is intended to serve as a data structure for an entire session/subject. Ben recommended we use a new NWB file for this, and there are some useful tools included in pynwb for TIFF conversion to nwb: https://neuroconv.readthedocs.io/en/main/conversion_examples_gallery/imaging/tiff.html

**Comment by Ahad-Allen** [comment]
Natalia's stack processing. code uses an average image over a 'chunk' of frames before splitting the file into the associated brain areas. We likely want to avoid this in order to package all the data from the stack into our output nwb file.

In order to avoid using too much storage/memory when gathering data for the writing of these files, we will likely want to load in a page at a time and then generate an intermediary file of split frames from that page. We can then use tifftools to concat the intermediary file into a merged file of rois from the area we are currently generating a tiff for before deleting the intermediary file. This should let us take full advantage of lazy loading for writing and reading and avoid having any large arrays which use a lot of memory or tons of intermediary files at once which take up a lot of storage.

**Comment by Ahad-Allen** [comment]
I've contacted Shiella to see if we can simplify the code by using a precalculated offset for the tiff files. We can still move forward with testing the code without this change, so I am not moving this external input for now. I'll update the script based on her response, however.

**Comment by jeromelecoq** [comment]
@Ahad-Allen to add tiff page to an ongoing tiff file to avoid duplication. Will explore the documentation.

**Comment by Ahad-Allen** [comment]
I was able to get the process working for the directory and can generate distinct output files. Now I am working on using the neuroconv code to package these into nwb files.

**Comment by Ahad-Allen** [comment]
Tim has some separated and denoised tiff files that he will share with us to try and package into the nwb format. this should let us package ~5gigs rather >200 and make processing a lot smoother/faster.

**Comment by Ahad-Allen** [comment]
Tim is going to send the files by the end of the week.

**Comment by Ahad-Allen** [comment]
Tim just shared the files with me, I am going to explore adding them into nwb format.

**Comment by jeromelecoq** [comment]
We are using both clean and raw averaged stack movies. We will put both in the same NWB files

**Comment by Ahad-Allen** [comment]
The raw movies seem to be split by tufts and somas. I asked jay about how we want to handle packaging the files associated with each brain area (is it 2 raw + 1 clean stack?) and he reached out to Tim for confirmation. In the mean time, I have a capsule on code ocean working for packaging the tiff files into the nwbs.

**Comment by Ahad-Allen** [comment]
I am able to package all 4 brain areas into an nwb file and have them each be stored as an image series. Each series is named after the relevant area. 


![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/87045911/f4fc1a5d-2239-41a2-a01e-0c67dc93704c)



![Image](https://github.com/AllenInstitute/OpenScopeNWB/assets/87045911/b4427181-f2ee-47fb-8367-71bd42203c46)

Once we are certain on how to handle the tufts + soma files, the only additional thing these files need should be the subject table.

**Comment by jeromelecoq** [comment]
@Ahad-Allen will reach out to Ben/Ryan to check best filename convention.

**Comment by jeromelecoq** [comment]
@Ahad-Allen will move it under processing

**Comment by Ahad-Allen** [comment]
Waiting on a response with regards to naming.

**Comment by jeromelecoq** [comment]
Tim confirmed the files were good
