### ISSUE TITLE
Trigger all remaining 2p that were fixed with stimulus name

### ISSUE THREAD

**Issue by jeromelecoq** [AllenInstitute/OpenScopeNWB#94]

**Comment by jeromelecoq** [comment]
@Ahad-Allen to add miore details here on ongoing process.

**Comment by Ahad-Allen** [comment]
There was originally a bug with LIMS causing 2p sessions to be posted without their stimulus name. Now that it has been resolved, we are running conversions for all of them.

**Comment by Ahad-Allen** [comment]
Satra sent me this code to work on renaming our old experiments as well https://github.com/catalystneuro/neuroconv/blob/main/src/neuroconv/tools/data_transfers.py#L290-L297, I will trigger that and then move to using this for the new sessions

**Comment by Ahad-Allen** [comment]
Using a modified version of the code, I am able to download the experiments one at a time, run dandi organize to rename them, and then attempt to use dandi upload to create the correct metadata and upload them. There were originally some issues with using Carter's script to grab all the correct versions of the files associated with a dandiset, due to package versioning issues with h5py (Carter uses a newer version of it then the AllenSDK supports), but I was able to avoid that by avoiding streaming any metadata at all and simply relying on using the file names that dandi can provide.

The only issue with this approach currently is the lack of an 'order_of_images' attribute associated with the images field of the processing field of the NWB files. This was added to the standard in 2022, so the image insertion code of the SDK does not include this. This is a confusing problem to tackle, however, because (at least as far I know), these attributes of an NWB file's fields are immutable. I tried to get around this by using 'pop' to remove the field entirely and add back in a temp version of it with the attribute added, but ran into the some other similar modification errors there.

I have asked satra about the best way to approach this problem and offered to create a dandi-cli issue if he finds that appropriate. I will update this issue as needed based on that.

**Comment by Ahad-Allen** [comment]
Satra asked me to post this information to the debug section of the dandi slack and I have done so. I will update this ticket and let everyone know if Satra, Ben, or Cody provide any updates.

**Comment by Ahad-Allen** [comment]
Ryan is going to look over the files to see if there are any issues. He think this may be caused by a bug with NWB inspector.

**Comment by Ahad-Allen** [comment]
Cody and Ryan got back. The problem was merely caused by a pynwb version error. By updating it to 2.2, we avoid the error!

**Comment by Ahad-Allen** [comment]
These are currently running
